# Generated by Django 4.0.3 on 2022-03-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auctionlisting_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
