# Generated by Django 4.0.3 on 2022-03-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_category_alter_auctionlisting_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
