# Generated by Django 4.0.3 on 2022-03-21 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_bid_bidder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='price',
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='current_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='auctions.bid'),
        ),
    ]
