# Generated by Django 4.0.3 on 2022-04-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_auctionlisting_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
